// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB40YxN37XGi7u6ZI8znLivJlUFZw-pYcM',
    appId: '1:614529458726:web:3fb25eb4ca6dfacdb17ce7',
    messagingSenderId: '614529458726',
    projectId: 'mirrors-store',
    authDomain: 'mirrors-store.firebaseapp.com',
    storageBucket: 'mirrors-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZw6cZOMAGPyXBVWO6q3lELxPcxg9sgZk',
    appId: '1:614529458726:android:a27f5e197f98dfcfb17ce7',
    messagingSenderId: '614529458726',
    projectId: 'mirrors-store',
    storageBucket: 'mirrors-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOSLIJkeck5_ZAHxbFhB5gJvCwbxQyuMc',
    appId: '1:614529458726:ios:5da9b4815183af16b17ce7',
    messagingSenderId: '614529458726',
    projectId: 'mirrors-store',
    storageBucket: 'mirrors-store.firebasestorage.app',
    iosBundleId: 'com.example.mirrorsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOSLIJkeck5_ZAHxbFhB5gJvCwbxQyuMc',
    appId: '1:614529458726:ios:5da9b4815183af16b17ce7',
    messagingSenderId: '614529458726',
    projectId: 'mirrors-store',
    storageBucket: 'mirrors-store.firebasestorage.app',
    iosBundleId: 'com.example.mirrorsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB40YxN37XGi7u6ZI8znLivJlUFZw-pYcM',
    appId: '1:614529458726:web:9752af2a2a9573c1b17ce7',
    messagingSenderId: '614529458726',
    projectId: 'mirrors-store',
    authDomain: 'mirrors-store.firebaseapp.com',
    storageBucket: 'mirrors-store.firebasestorage.app',
  );
}
